### ISSUE TITLE
R.java file not generated

### ISSUE THREAD

**Issue by hamzahalvanaa** [cslrfid/CS108-Android-Java-App#14]
Hi @ksclam, I had tried to find R.java class file in the project but there's nothing, could you help me how to achieve?

**Comment by ksclam** [comment]
Kindly note that starting from Android 3.6 or above, the new Android Gradle Plugin generates the corresponding bytecode directly and does not make the intermediate R.java file.

https://android-developers.googleblog.com/2020/02/android-studio-36.html
